/**
 * ScanLogic branded PDF layout — shared fonts, colours, headers & footers.
 * Colours match @theme brand palette in index.css.
 */

import { jsPDF } from 'jspdf'
import { BRAND_NAME, BRAND_SUITE_NAME } from '@/lib/brand'

export const PDF_THEME = {
  brand600: [79, 70, 229],
  brand700: [67, 56, 202],
  brand900: [49, 46, 129],
  brand50: [238, 242, 255],
  brand200: [199, 210, 254],
  slate50: [248, 250, 252],
  slate800: [30, 41, 59],
  slate500: [100, 116, 139],
  slate200: [226, 232, 240],
  white: [255, 255, 255],
  margin: 20,
  labelWidth: 48,
  contentWidth: 170,
  footerY: 282,
}

export const PDF_FONTS = {
  family: 'helvetica',
  titleSize: 16,
  sectionSize: 11,
  bodySize: 10,
  labelSize: 8,
  footerSize: 7,
}

const DEFAULT_DISCLAIMER =
  'Generated by ScanLogic Business Suite — preparation document only, not legal or tax advice.'

export function createBrandedPdf(options = {}) {
  return new jsPDF({
    orientation: options.landscape ? 'landscape' : 'portrait',
    unit: 'mm',
    format: options.format || 'a4',
  })
}

export function pageWidth(pdf) {
  return pdf.internal.pageSize.getWidth()
}

export function pageHeight(pdf) {
  return pdf.internal.pageSize.getHeight()
}

/** Branded header band + document title. Returns start Y for body content. */
export function drawBrandedHeader(pdf, { title, subtitle, module } = {}) {
  const w = pageWidth(pdf)
  const bandH = 26

  pdf.setFillColor(...PDF_THEME.brand900)
  pdf.rect(0, 0, w, bandH, 'F')

  pdf.setFillColor(...PDF_THEME.brand600)
  pdf.rect(0, bandH, w, 1.2, 'F')

  pdf.setTextColor(...PDF_THEME.white)
  pdf.setFont(PDF_FONTS.family, 'bold')
  pdf.setFontSize(10)
  pdf.text(BRAND_SUITE_NAME, PDF_THEME.margin, 11)

  pdf.setFont(PDF_FONTS.family, 'normal')
  pdf.setFontSize(7.5)
  pdf.text(module || BRAND_NAME, PDF_THEME.margin, 17)

  pdf.setFontSize(7)
  pdf.text(new Date().toLocaleDateString('de-DE'), w - PDF_THEME.margin, 11, { align: 'right' })

  let y = bandH + 14
  pdf.setTextColor(...PDF_THEME.slate800)
  pdf.setFont(PDF_FONTS.family, 'bold')
  pdf.setFontSize(PDF_FONTS.titleSize)
  pdf.text(title || 'Document', PDF_THEME.margin, y)
  y += 7

  if (subtitle) {
    pdf.setFont(PDF_FONTS.family, 'normal')
    pdf.setFontSize(PDF_FONTS.bodySize)
    pdf.setTextColor(...PDF_THEME.slate500)
    const subLines = pdf.splitTextToSize(subtitle, PDF_THEME.contentWidth)
    pdf.text(subLines, PDF_THEME.margin, y)
    y += subLines.length * 4.5 + 2
  }

  return y + 4
}

export function drawSectionTitle(pdf, y, title) {
  pdf.setDrawColor(...PDF_THEME.brand600)
  pdf.setLineWidth(0.5)
  pdf.line(PDF_THEME.margin, y, PDF_THEME.margin + 36, y)

  pdf.setFont(PDF_FONTS.family, 'bold')
  pdf.setFontSize(PDF_FONTS.sectionSize)
  pdf.setTextColor(...PDF_THEME.brand700)
  pdf.text(title, PDF_THEME.margin, y + 7)
  return y + 14
}

/** Label + value row with subtle background stripe. */
export function drawFieldRow(pdf, y, label, value, { alt = false } = {}) {
  const x = PDF_THEME.margin
  const val = value != null && String(value).trim() ? String(value).trim() : '—'

  pdf.setFillColor(...(alt ? PDF_THEME.brand50 : PDF_THEME.slate50))
  pdf.rect(x - 2, y - 4.5, PDF_THEME.contentWidth + 4, 9, 'F')

  pdf.setFont(PDF_FONTS.family, 'bold')
  pdf.setFontSize(PDF_FONTS.labelSize)
  pdf.setTextColor(...PDF_THEME.slate500)
  pdf.text(label, x, y)

  pdf.setFont(PDF_FONTS.family, 'normal')
  pdf.setFontSize(PDF_FONTS.bodySize)
  pdf.setTextColor(...PDF_THEME.slate800)
  const lines = pdf.splitTextToSize(val, PDF_THEME.contentWidth - PDF_THEME.labelWidth)
  pdf.text(lines, x + PDF_THEME.labelWidth, y)

  return y + Math.max(9, lines.length * 4.8) + 1.5
}

export function drawBodyParagraph(pdf, y, text, maxWidth = PDF_THEME.contentWidth) {
  pdf.setFont(PDF_FONTS.family, 'normal')
  pdf.setFontSize(PDF_FONTS.bodySize)
  pdf.setTextColor(...PDF_THEME.slate800)
  const lines = pdf.splitTextToSize(text || '', maxWidth)
  pdf.text(lines, PDF_THEME.margin, y)
  return y + lines.length * 4.8 + 4
}

export function drawDisclaimerBox(pdf, y, text) {
  const x = PDF_THEME.margin
  const w = PDF_THEME.contentWidth
  pdf.setFillColor(...PDF_THEME.brand50)
  pdf.setDrawColor(...PDF_THEME.brand200)
  pdf.setLineWidth(0.3)
  pdf.roundedRect(x - 2, y - 3, w + 4, 14, 2, 2, 'FD')

  pdf.setFont(PDF_FONTS.family, 'italic')
  pdf.setFontSize(PDF_FONTS.labelSize)
  pdf.setTextColor(...PDF_THEME.brand700)
  const lines = pdf.splitTextToSize(text, w - 4)
  pdf.text(lines, x, y + 2)
  return y + 16
}

/** Ensure enough vertical space; adds branded continuation page if needed. */
export function ensureSpace(pdf, y, needed, { title, module } = {}) {
  const limit = PDF_THEME.footerY - 8
  if (y + needed <= limit) return y
  pdf.addPage()
  return drawBrandedHeader(pdf, {
    title: title || 'Fortsetzung',
    subtitle: '—',
    module,
  })
}

export function applyBrandedFooters(pdf, disclaimer = DEFAULT_DISCLAIMER) {
  const total = pdf.internal.getNumberOfPages()
  const w = pageWidth(pdf)
  const h = pageHeight(pdf)

  for (let i = 1; i <= total; i++) {
    pdf.setPage(i)
    pdf.setDrawColor(...PDF_THEME.brand200)
    pdf.setLineWidth(0.25)
    pdf.line(PDF_THEME.margin, h - 16, w - PDF_THEME.margin, h - 16)

    pdf.setFont(PDF_FONTS.family, 'normal')
    pdf.setFontSize(PDF_FONTS.footerSize)
    pdf.setTextColor(...PDF_THEME.slate500)
    pdf.text(disclaimer, PDF_THEME.margin, h - 11, { maxWidth: w - PDF_THEME.margin * 2 - 30 })
    pdf.setTextColor(...PDF_THEME.brand600)
    pdf.text(`${BRAND_NAME} · ${i}/${total}`, w - PDF_THEME.margin, h - 11, { align: 'right' })
  }
}

export function saveBrandedPdf(pdf, filename, disclaimer) {
  applyBrandedFooters(pdf, disclaimer)
  pdf.save(filename)
}

/** Branded multi-section document (legal packs, contracts). */
export function buildBrandedSectionsPdf(sections, { module, disclaimer } = {}) {
  const pdf = createBrandedPdf()
  let first = true

  sections.forEach((sec) => {
    if (!first) pdf.addPage()
    first = false
    let y = drawBrandedHeader(pdf, {
      title: sec.title,
      subtitle: sec.subtitle,
      module: module || 'Website-Rechtliches',
    })
    y = drawBodyParagraph(pdf, y, sec.content)
  })

  applyBrandedFooters(pdf, disclaimer)
  return pdf
}
